# Generated by Django 5.2.9 on 2026-01-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='ticket_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_processing', 'Payment Processing'), ('registered', 'Registered'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
