# Generated by Django 5.2.9 on 2026-01-01 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0010_remove_enrollment_course_remove_lesson_course_and_more"),
        ("docs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description/excerpt of the documentation",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Main content (supports markdown)"),
                ),
                (
                    "chapter_number",
                    models.IntegerField(default=0, help_text="Chapter ordering"),
                ),
                (
                    "section_number",
                    models.IntegerField(default=0, help_text="Section within chapter"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="docs/images/"),
                ),
                (
                    "diagram_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="docs/diagrams/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="published",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for grouping (e.g., Python, Django, Flask)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documentation",
                "db_table": "blog_documentation",
                "ordering": ["chapter_number", "section_number"],
            },
        ),
    ]
