# Generated by Django 5.2.8 on 2026-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_video_file',
            field=models.FileField(blank=True, help_text='Upload a video file directly (mp4, etc.)', null=True, upload_to='courses/previews/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file directly', null=True, upload_to='courses/lessons/'),
        ),
    ]
