# Generated by Django 5.2.8 on 2026-01-01 15:26

import django.db.models.deletion
from django.db import migrations, models


def copy_tags_and_categories(apps, schema_editor):
    """Copy tags and categories from blog app to courses app"""
    db_alias = schema_editor.connection.alias

    # Copy tags from blog_tag to courses_tag
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO courses_tag (id, name, slug)
            SELECT id, name, slug FROM blog_tag
        """)

        # Copy categories from blog_category to courses_category
        cursor.execute("""
            INSERT INTO courses_category (id, name, slug, description)
            SELECT id, name, slug, description FROM blog_category
        """)


def reverse_copy(apps, schema_editor):
    """Reverse migration - just delete the copied data"""
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM courses_tag")
        cursor.execute("DELETE FROM courses_category")


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_preview_video_file_lesson_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'courses_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Course Tag',
                'verbose_name_plural': 'Course Tags',
                'db_table': 'courses_tag',
            },
        ),
        migrations.RunPython(copy_tags_and_categories, reverse_copy),
        migrations.AddField(
            model_name='course',
            name='preview_video_url_native',
            field=models.URLField(blank=True, help_text='Direct video URL (.mp4, .webm, etc.) or other video platform', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_url_vimeo',
            field=models.URLField(blank=True, help_text='Vimeo video URL (e.g., https://vimeo.com/xxxxx)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_url_youtube',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=xxxxx)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url_native',
            field=models.URLField(blank=True, help_text='Direct video URL (.mp4, .webm, etc.) or other video platform', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url_vimeo',
            field=models.URLField(blank=True, help_text='Vimeo video URL (e.g., https://vimeo.com/xxxxx)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url_youtube',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=xxxxx)', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_video_file',
            field=models.FileField(blank=True, help_text='Upload a video file directly (mp4, webm, etc.)', null=True, upload_to='courses/previews/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file directly (mp4, webm, etc.)', null=True, upload_to='courses/lessons/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='courses.tag'),
        ),
    ]
