# Generated by Django 5.2.8 on 2025-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_documentation_post_post_type_postvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='doc_order',
            field=models.IntegerField(default=0, help_text='Order for documentation chapters'),
        ),
    ]
