# Generated by Django 5.2.9 on 2025-12-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Main content of the post (supports markdown)'),
        ),
    ]
