# Generated by Django 5.2.9 on 2025-12-30 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentation",
            name="code_example",
        ),
        migrations.AddField(
            model_name="documentation",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category for grouping (e.g., Python, Django, Flask)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.category",
            ),
        ),
        migrations.AddField(
            model_name="documentation",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="docs/images/"),
        ),
        migrations.AddField(
            model_name="documentation",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentation",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="content",
            field=models.TextField(help_text="Main content (supports markdown)"),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="description",
            field=models.TextField(
                help_text="Brief description/excerpt of the documentation",
                max_length=300,
            ),
        ),
    ]
