# Generated by Django 5.2.9 on 2025-12-30 16:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_documentation_code_example_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="post",
            name="doc_order",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(
                help_text="Rich text content for posts and blogs"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("post", "Community Post"), ("blog", "Blog Article")],
                default="post",
                max_length=10,
            ),
        ),
    ]
