# Generated by Django 5.2.9 on 2026-01-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_pricingplan_course_coursechapter_lesson_enrollment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.RemoveField(
            model_name="coursechapter",
            name="course",
        ),
        migrations.AlterUniqueTogether(
            name="coursechapter",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="documentation",
            name="author",
        ),
        migrations.RemoveField(
            model_name="documentation",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="completed_lessons",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="pricing_plan",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="enrollment",
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="lesson",
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseChapter",
        ),
        migrations.DeleteModel(
            name="Documentation",
        ),
        migrations.DeleteModel(
            name="PricingPlan",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="LessonProgress",
        ),
    ]
